# FindFusionLibFFI.cmake
# Find libffi. Sets FUSION_LIBFFI_FOUND and creates LibFFI::LibFFI.
# Include from root CMakeLists.txt (so target is global) and runtime_c/CMakeLists.txt.
# Install with: sudo apt install libffi-dev

if(TARGET LibFFI::LibFFI)
  set(FUSION_LIBFFI_FOUND TRUE)
  set(FUSION_LIBFFI_FOUND TRUE PARENT_SCOPE)
  return()
endif()

find_package(PkgConfig QUIET)
set(FUSION_LIBFFI_FOUND FALSE)
if(PkgConfig_FOUND)
  pkg_check_modules(LibFFI QUIET libffi)
  if(LibFFI_FOUND)
    find_library(_LibFFI_LIBRARY_PC ffi PATHS ${LibFFI_LIBRARY_DIRS} NO_DEFAULT_PATH)
    if(_LibFFI_LIBRARY_PC)
      set(LibFFI_LIBRARY "${_LibFFI_LIBRARY_PC}")
    else()
      find_library(LibFFI_LIBRARY ffi)
    endif()
    unset(_LibFFI_LIBRARY_PC CACHE)
    if(LibFFI_LIBRARY)
      set(FUSION_LIBFFI_FOUND TRUE)
      set(FUSION_LIBFFI_FOUND TRUE PARENT_SCOPE)
      add_library(LibFFI::LibFFI UNKNOWN IMPORTED)
      set_target_properties(LibFFI::LibFFI PROPERTIES
        IMPORTED_LOCATION "${LibFFI_LIBRARY}"
        INTERFACE_INCLUDE_DIRECTORIES "${LibFFI_INCLUDE_DIRS}")
    endif()
  endif()
endif()
if(NOT FUSION_LIBFFI_FOUND)
  find_path(LibFFI_INCLUDE_DIR ffi.h)
  find_library(LibFFI_LIBRARY ffi)
  if(LibFFI_INCLUDE_DIR AND LibFFI_LIBRARY)
    set(FUSION_LIBFFI_FOUND TRUE)
    set(FUSION_LIBFFI_FOUND TRUE PARENT_SCOPE)
    add_library(LibFFI::LibFFI UNKNOWN IMPORTED)
    set_target_properties(LibFFI::LibFFI PROPERTIES
      IMPORTED_LOCATION "${LibFFI_LIBRARY}"
      INTERFACE_INCLUDE_DIRECTORIES "${LibFFI_INCLUDE_DIR}")
  endif()
endif()
# If we "found" libffi (e.g. from cache) but ffi.h is not actually there, use stub
if(FUSION_LIBFFI_FOUND)
  if(LibFFI_FOUND)
    set(_ffi_search_dirs ${LibFFI_INCLUDE_DIRS})
  else()
    set(_ffi_search_dirs ${LibFFI_INCLUDE_DIR})
  endif()
  find_file(_ffi_h ffi.h PATHS ${_ffi_search_dirs} NO_DEFAULT_PATH)
  if(NOT _ffi_h)
    message(STATUS "libffi header ffi.h not found, using FFI stub")
    set(FUSION_LIBFFI_FOUND FALSE)
    set(FUSION_LIBFFI_FOUND FALSE PARENT_SCOPE)
  endif()
  unset(_ffi_h CACHE)
  unset(_ffi_search_dirs)
endif()
if(NOT FUSION_LIBFFI_FOUND)
  message(STATUS "libffi not found: FFI will use stub (install with: sudo apt install libffi-dev)")
endif()
