# SanitizeLLVMLibs.cmake
# LLVM imported targets add absolute .so paths (libtinfo, libz) via INTERFACE_LINK_LIBRARIES,
# causing "No rule to make target ... libtinfo.so". We resolve each LLVM component to its
# IMPORTED_LOCATION (.a path) and pass as libraries (not link options) so they appear after
# object files and fusion_compiler on the link line—required for static linking.
# Sets: FUSION_LLVM_LIBRARY_PATHS (abs paths for .a), FUSION_LLVM_LIBS_SANITIZED (-l names for .so only).

set(FUSION_LLVM_LIBRARY_PATHS "")
set(FUSION_LLVM_LIBS_SANITIZED "")
foreach(_lib ${FUSION_LLVM_LIBS})
  if(IS_ABSOLUTE "${_lib}" AND _lib MATCHES "\\.so(\\..*)?$")
    get_filename_component(_name "${_lib}" NAME)
    string(REGEX REPLACE "^lib" "" _name "${_name}")
    string(REGEX REPLACE "\\.so(\\..*)?$" "" _name "${_name}")
    list(APPEND FUSION_LLVM_LIBS_SANITIZED "${_name}")
  elseif(TARGET "${_lib}")
    get_target_property(_loc "${_lib}" IMPORTED_LOCATION)
    if(NOT _loc)
      get_target_property(_loc "${_lib}" IMPORTED_LOCATION_RELEASE)
    endif()
    if(NOT _loc)
      foreach(_cfg RELEASE RELWITHDEBINFO MINSIZEREL DEBUG)
        get_target_property(_loc "${_lib}" "IMPORTED_LOCATION_${_cfg}")
        if(_loc)
          break()
        endif()
      endforeach()
    endif()
    if(_loc)
      get_filename_component(_abs "${_loc}" ABSOLUTE)
      # Pre-built LLVM 18+ tarballs may put .a in lib/x86_64-unknown-linux-gnu/ instead of lib/
      if(NOT EXISTS "${_abs}")
        get_filename_component(_libdir "${_abs}" DIRECTORY)
        get_filename_component(_name "${_abs}" NAME)
        if(EXISTS "${_libdir}/x86_64-unknown-linux-gnu/${_name}")
          set(_abs "${_libdir}/x86_64-unknown-linux-gnu/${_name}")
        endif()
      endif()
      if(EXISTS "${_abs}")
        list(APPEND FUSION_LLVM_LIBRARY_PATHS "${_abs}")
      endif()
    else()
      list(APPEND FUSION_LLVM_LIBS_SANITIZED "${_lib}")
    endif()
  else()
    list(APPEND FUSION_LLVM_LIBS_SANITIZED "${_lib}")
  endif()
endforeach()
list(REMOVE_DUPLICATES FUSION_LLVM_LIBRARY_PATHS)
list(REMOVE_DUPLICATES FUSION_LLVM_LIBS_SANITIZED)
message(STATUS "FUSION_LLVM_LIBRARY_PATHS = ${FUSION_LLVM_LIBRARY_PATHS}")
message(STATUS "FUSION_LLVM_LIBS_SANITIZED = ${FUSION_LLVM_LIBS_SANITIZED}")
